// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNgRBGyglIEmo8eXyMhsPKA-2kNJLvASI',
    appId: '1:722918725757:web:bee4176999af8c44c23914',
    messagingSenderId: '722918725757',
    projectId: 'toyidea-smartphone-app',
    authDomain: 'toyidea-smartphone-app.firebaseapp.com',
    storageBucket: 'toyidea-smartphone-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCepgg6ctfVPHegqIMpVmCy7SvMSAapKp0',
    appId: '1:722918725757:android:7ac1f1e282f39628c23914',
    messagingSenderId: '722918725757',
    projectId: 'toyidea-smartphone-app',
    storageBucket: 'toyidea-smartphone-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjhMivHtQO9mI6nHTHELb-p7Y5jJiSIW4',
    appId: '1:722918725757:ios:064e1e63f82c2ac8c23914',
    messagingSenderId: '722918725757',
    projectId: 'toyidea-smartphone-app',
    storageBucket: 'toyidea-smartphone-app.appspot.com',
    iosClientId: '722918725757-0al6u01oqu655c8b39eukir8jdgevqkr.apps.googleusercontent.com',
    iosBundleId: 'com.example.toyideaSmartphoneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjhMivHtQO9mI6nHTHELb-p7Y5jJiSIW4',
    appId: '1:722918725757:ios:064e1e63f82c2ac8c23914',
    messagingSenderId: '722918725757',
    projectId: 'toyidea-smartphone-app',
    storageBucket: 'toyidea-smartphone-app.appspot.com',
    iosClientId: '722918725757-0al6u01oqu655c8b39eukir8jdgevqkr.apps.googleusercontent.com',
    iosBundleId: 'com.example.toyideaSmartphoneApp',
  );
}
